### PR TITLE
Update module name to github.com/stellar/throttled

### PR DESCRIPTION
**Pull request by leighmcculloch**
### Summary
Update module name to github.com/stellar/throttled.

### Goal and scope
@MonsieurNicolas made the suggestion https://github.com/stellar/go/pull/1642#issuecomment-524483011 that we should take @bartekn's into the @stellar org. He setup the project and I pushed the `master` branch from over there. This change updates the imports and package name internally so that it knows itself at this repo address.

Related to stellar/go#1634

### CODE REVIEW

**Comment by leighmcculloch** [comment]
The builds pass on the latest version of Go but not the myriad of older versions of Go which is understandable.

**Comment by leighmcculloch** [comment]
There's quite a few things in the build scripts that need updating, but it passes on Go 1.12, and this code is code we're already importing in it's current state, so I think we should merge this even though the other builds are failing, and then discuss how much we want to invest in cleaning up this repo.

**Comment by leighmcculloch** [comment]
I fixed the TravisCI config in #2. Those changes are temporarily showing up in this diff because I merged the config into this branch to check that the tests pass with these changes. After #2 is merged this PRs diff will be smaller.

**Review by tomquisel — APPROVED** [review]
Looks good! Why isn't the Makefile needed?

**Comment by leighmcculloch** [comment]
Travis knows how to build and test go projects without any configuration. The makefile was causing travis to run `make install`, and the makefile contained unnecessary `go get` commands. Since we rely on using straight up go commands in our other repos and the makefile contained about 50% things that we don't need, I figured it was better to drop it in our diverged fork than to spend time cleaning it up.

**Pull request merged**
